export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_USER_ROOM = "GET_USER_ROOM";
export const GET_NETWORK_HANDLER = "GET_NETWORK_HANDLER";