module.exports = Object.freeze({
  PLAYER_WIDTH: 32,
  PLAYER_HEIGHT: 32,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 400,
  PLAYER_JUMP: 800,
  PLAYER_GRAVITY: 50,
  PLAYER_FIRE_COOLDOWN: 0.5,

  BULLET_WIDTH: 32,
  BULLET_HEIGHT: 10,
  BULLET_SPEED: 600,
  BULLET_DAMAGE: 10,

  REFLECT_BULLET_BOUNCES: 5,
  REFLECT_BULLET_COOLDOWN: 20,

  DRILL_WIDTH: 32,
  DRILL_HEIGHT: 24,
  DRILL_SPEED: 300,

  BOMB_WIDTH: 32,
  BOMB_HEIGHT: 32,
  BOMB_SPEED: 600,
  BOMB_GRAVITY: 10,
  BOMB_COOLDOWN: 20,
  BOMB_LIFETIME: 100,

  MINE_WIDTH: 32,
  MINE_HEIGHT: 8,
  MINE_SPEED: 100,
  MINE_COOLDOWN: 50,

  EXPLOSION_WIDTH: 64,
  EXPLOSION_HEIGHT: 64,
  EXPLOSION_DAMAGE: 10,

  PLATFORM_RESPAWN: 500,

  POWERUP_WIDTH: 20,
  POWERUP_HEIGHT: 20,
  PLAYER_POWERUP_WIDTH: 10,
  PLAYER_POWERUP_HEIGHT: 10,


  HEALTHBAR_WIDTH: 32,
  HEALTHBAR_HEIGHT: 8,

  SCORE_BULLET_HIT: 20,
  SCORE_PER_SECOND: 1,

  WIDTH: 1024, 
  HEIGHT: 1024/12 * 9,
  MAP_SIZE: 3000,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    KEYPRESS: 'keypress',
    KEYUP: "keyup",
    CLICK: "click",
    GAME_OVER: 'dead',
  },
});
