module.exports = Object.freeze({
    PLAYER: 1,
    BULLET: 2,
    PLATFORM: 3,
    POWERUP: 4,
    NO_POWERUP: 5,
    SHIELD_POWERUP: 6,
    DRILL_POWERUP: 7,
    BOMB_POWERUP: 8,
    MINE_POWERUP: 9,
    REFLECT_POWERUP: 10,
    DRILL: 11,
    BOMB: 12,
    MINE: 13,
    EXPLOSION: 14,
    NO_CHARACTER: 15,
    PANDA: "PANDA",
    SEAL: "SEAL",
    DINO: "DINO",
    EAGLE: "EAGLE",
    BAMBOO_STORM: 20,
    BAMBOO: 21,
    LASER: 22,
    FIRE_CLOUD: 23,
    TELEPORT_BULLET: 24
});